<a href="https://colab.research.google.com/github/jpquach1/Pytorch_Udemy_Certificate/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [24]:
# Import torch
import torch


# Create random tensor
tensor_A = torch.rand((7,7))
tensor_A, tensor_A.shape


(tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196],
         [0.2147, 0.2816, 0.6679, 0.7878, 0.5070, 0.3055, 0.7738],
         [0.2259, 0.3826, 0.9717, 0.5921, 0.5352, 0.6686, 0.3781],
         [0.9278, 0.0922, 0.3625, 0.4136, 0.2943, 0.3762, 0.8099],
         [0.7743, 0.5278, 0.9356, 0.1470, 0.2019, 0.7259, 0.4731],
         [0.0444, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278],
         [0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 0.8640, 0.3388]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [25]:
# Create another random tensor
tensor_B = torch.rand((1,7))
# Perform matrix multiplication
result_3 = torch.matmul(tensor_A,tensor_B.T)
result_3, result_3.shape


(tensor([[1.7488],
         [2.0786],
         [2.0697],
         [1.5989],
         [1.7942],
         [1.9002],
         [1.4212]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
tensor_C = torch.rand((7,7))
tensor_D = torch.rand((1,7))

# Matrix multiply tensors
torch.matmul(tensor_C,tensor_D.T), torch.matmul(tensor_C,tensor_D.T).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on the GPU
cuda_seed = 1234
torch.cuda.manual_seed(cuda_seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
torch.manual_seed(cuda_seed)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_gpu_A = torch.rand((2,3))
tensor_gpu_A = tensor_gpu_A.to(device)
tensor_gpu_B = torch.rand((2,3))
tensor_gpu_B = tensor_gpu_B.to(device)

print(tensor_gpu_A)
print(tensor_gpu_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
matrix_multiplication = torch.matmul(tensor_gpu_A, tensor_gpu_B.T)
matrix_multiplication,  matrix_multiplication.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
print(torch.max(matrix_multiplication))
# Find min
print(torch.min(matrix_multiplication))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max
print(torch.argmax(matrix_multiplication))

# Find arg min
print(torch.argmin(matrix_multiplication))


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
seed = 7
torch.manual_seed(seed)

# Create random tensor
tensor_10 = torch.rand((1, 1, 1, 10))

# Remove single dimensions
tensor_10_squeezed = tensor_10.squeeze()

# Print out tensors and their shapes
print(tensor_10 , tensor_10.shape)
print(tensor_10_squeezed, tensor_10_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
