<a href="https://colab.research.google.com/github/jpquach1/Pytorch_Udemy_Certificate/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Ressource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


2.0.0 c'est la version de torch et 11.8 est la version de cuda

In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` -= https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim
#Number of squared bracket = nombre de crochets

1

In [10]:
vector.shape
# 2 x 1 elements

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
 TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Le chiffre 1 dans le shape correspond au premier crochet  
Le chiffre 3 correspond au nombre d'élément dans le 2 ème crochets  
Le chifre 3 correspon au nombre d'élément dans le 3eme crochets  

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [32]:
# Create a random tensors of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7739, 0.4048, 0.0413, 0.6257],
        [0.2969, 0.9355, 0.8722, 0.3835],
        [0.7541, 0.4827, 0.1032, 0.4744]])

In [33]:
random_tensor.ndim

2

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width,color channels (R,G,B) # the color can come first
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [39]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
# Voici comment on crée un mask de zeros
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [44]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [53]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.range(0,10)
# Mais la meilleure façon d'utiliser range c'est arange

<ipython-input-53-e0ed36cd369b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [54]:
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big erros you'll run into with Pytorch & deep learning:  
1. Tensors not right datatype  
2. Tensors not right shape
3. Tensors not on the right device  

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [68]:
# Float 32 tensor # default data type in pytorch # These are the most important parameters to use
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor(e.g float32 or float16)  # We used torch.float16 # these are the most used
                               device=None, # What device is your tensor on# l'un peut être sur le cpu et l'autre sur le gpu # cpu or cuda
                               requires_grad=False) # whether or not to track gradients with this tnesors operations #search for a certain gradients
float_32_tensor

# plus on augmente le nombre de bit plus la précision de la représentation du nombre va prendre de la place dans la mémoire

tensor([3., 6., 9.])

In [69]:
float_32_tensor.dtype

torch.float32

In [70]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [71]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])